<a href="https://colab.research.google.com/github/Ridzzz0Alam/Data_Science/blob/main/Assignment_on_module_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ecommerce Purchases Exercise Overview

Hi Guys,<br>
After a crash course on pandas for data analysis, its time to do some practice!!!<br>
Because of privacy issues, I have created a fake dataset here with 30K entries. <br>
The situation is, customers are providing some personal information while purchasing stuff on-line or in-store. For some reasons, your client wants to know the answer to some of his questions from the dataset, let's try to help him!.<br>

*Feel free to consult the solutions if needed. Please note, the tasks given in the exercises, can be solved in different ways. Try your best answer and compare with the solutions.* <br>
&#9758; The dataset is provided in the course downloads.

**1. Import Pandas and Read the csv file.**

In [1]:
import pandas as pd

cust = pd.read_csv("Cust_Purch_FakeData.csv")
cust.head()

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
0,Dr.,Ray,Morton,sebvajom@kol.km,Male,38,Medtronic Inc.,Health Therapist,(987) 619-2695,B6V 3W3,MB,5020000000000230,05/2018,Solo,8.36,Blue,126.23.139.2,Sunday,pm,04/05/1930
1,Miss,Claudia,Rodriquez,acu@jatsot.ug,Female,51,"Ames Department Stores, Inc.",Health Therapist,(356) 736-7352,G7M 5F3,SK,5020000000000230,07/2028,Visa,68.31,Black,106.198.76.211,Tuesday,am,12/20/1926
2,Miss,Harry,Meyer,zuz@lo.wf,Female,51,CSX Corp.,Political Scientist,(539) 246-1806,A0Z 6P9,NS,6300000000000000,02/2023,Switch,34.65,Black,186.150.187.29,Wednesday,pm,08/20/1931
3,Miss,Edith,Gilbert,hansohsi@jupec.md,Female,55,Murphy Oil Corporation,Transportation Manager,(984) 962-7494,P9I 9H3,YT,3530000000000000,02/2028,Maestro,64.59,White,80.140.57.161,Saturday,am,06/18/2001
4,Dr.,Lura,Murphy,webediti@je.st,Female,20,PETsMART Inc,Statistician,(902) 568-9748,S1A 6K0,ON,4030000000000000,10/2025,Diners Club International,20.83,Yellow,211.103.43.41,Friday,pm,06/14/2045

**2. Its good idea to see how the data look like, display first 5 rows of your data-set.**

In [2]:
# Code here please

In [2]:
cust.head()

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
0,Dr.,Ray,Morton,sebvajom@kol.km,Male,38,Medtronic Inc.,Health Therapist,(987) 619-2695,B6V 3W3,MB,5020000000000230,05/2018,Solo,8.36,Blue,126.23.139.2,Sunday,pm,04/05/1930
1,Miss,Claudia,Rodriquez,acu@jatsot.ug,Female,51,"Ames Department Stores, Inc.",Health Therapist,(356) 736-7352,G7M 5F3,SK,5020000000000230,07/2028,Visa,68.31,Black,106.198.76.211,Tuesday,am,12/20/1926
2,Miss,Harry,Meyer,zuz@lo.wf,Female,51,CSX Corp.,Political Scientist,(539) 246-1806,A0Z 6P9,NS,6300000000000000,02/2023,Switch,34.65,Black,186.150.187.29,Wednesday,pm,08/20/1931
3,Miss,Edith,Gilbert,hansohsi@jupec.md,Female,55,Murphy Oil Corporation,Transportation Manager,(984) 962-7494,P9I 9H3,YT,3530000000000000,02/2028,Maestro,64.59,White,80.140.57.161,Saturday,am,06/18/2001
4,Dr.,Lura,Murphy,webediti@je.st,Female,20,PETsMART Inc,Statistician,(902) 568-9748,S1A 6K0,ON,4030000000000000,10/2025,Diners Club International,20.83,Yellow,211.103.43.41,Friday,pm,06/14/2045

**3. How many entries your data have?
Can you tell the no. of columns in your data?**

In [4]:
# Code here please

In [3]:
n_rows, n_cols = cust.shape
print("Rows:", n_rows)
print("Columns:", n_cols)

Rows: 30000
Columns: 20

**4. What are the max and min ages of your customer? Can you find mean of your customer?**

In [6]:
# Code here please

In [4]:
min_age = cust["age"].min()
max_age = cust["age"].max()
mean_age = cust["age"].mean()

print("Min age:", min_age)
print("Max age:", max_age)
print("Mean age:", mean_age)

Min age: 18
Max age: 65
Mean age: 41.550066666666666

**5. What are the three most common customer's names?**<br>
&#9989; [<code>**value_counts()**</code>](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html) returns object containing counts of unique values. The resulting object will be in descending order so that the first element is the most frequently-occurring element. Excludes NA values by default.

In [8]:
# Code here please

In [5]:
cust["first"].value_counts().head(3)

first
Willie     130
Francis    124
Eula        86
Name: count, dtype: int64

**6. Two customers have the same phone number, can you find those customers**?

In [10]:
# Code here please

In [6]:
# lets find what phone number is twice!
dup_phone_rows = cust[cust["phone"].duplicated(keep=False)]
dup_phone_rows[["first", "last", "phone"]]

    first   last           phone
15  Lilly  Tyler  (263) 382-8004
16  Peter   Cain  (263) 382-8004

In [12]:
# Code here please

In [7]:
# Now we know the phone number, let's find out the other stuff!
(cust["profession"] == "Structural Engineer").sum()

np.int64(87)

**7. How many customers have profession "Structural Engineer"?**

In [14]:
# Code here please

In [8]:
(cust["profession"] == "Structural Engineer").sum()

np.int64(87)

**8. How many male customers are 'Structural Engineer'?**

In [15]:
# Code here please

In [9]:
cust[(cust["profession"] == "Structural Engineer") & (cust["gender"] == "Male")].shape[0]

43

**9. Find out the female Structural Engineers from province Alberta (AB)?**

In [16]:
# Code here please

In [10]:
female_struct_ab = cust[
    (cust["profession"] == "Structural Engineer")
    & (cust["gender"] == "Female")
    & (cust["province"] == "AB")
]
female_struct_ab

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
8858,Dr.,Roy,Stanley,apiunvo@ehasom.ir,Female,39,Cincinnati Financial Corp.,Structural Engineer,(876) 758-2929,N5A 6L2,AB,6300000000000000,02/2022,InstaPayment,31.86,Red,165.249.159.57,Sunday,pm,12/25/1903
9058,Mr.,Lora,Kennedy,dennap@rabac.se,Female,51,BJ Services Company,Structural Engineer,(305) 786-6959,N3R 4B7,AB,201000000000000,06/2019,Diners Club United States & Canada,53.29,Black,42.216.243.206,Thursday,pm,06/06/2028
24736,Mrs.,Nell,Richards,dob@me.ki,Female,18,Telephone & Data Systems Inc,Structural Engineer,(262) 681-5018,N3Y 3G2,AB,347000000000000,07/2028,American Express,76.28,Blue,91.16.30.156,Wednesday,pm,07/14/1951
29865,Mrs.,Don,McDaniel,naf@zudu.bj,Female,37,Anadarko Petroleum Corporation,Structural Engineer,(238) 789-2825,B4A 8Q9,AB,5610000000000000,12/2022,Mastercard,62.71,Blue,162.233.117.142,Sunday,pm,11/03/1989

**10. What is the max, min and average spending?**

In [17]:
# Code here please

In [11]:
cust["price(CAD)"].agg(["min", "max", "mean"])

min       0.000000
max     100.000000
mean     49.990775
Name: price(CAD), dtype: float64

**11. Who did not spend anything? Company wants to send a deal to encourage the customer to buy stuff!**

In [18]:
# Code here please

In [12]:
no_spend = cust[cust["price(CAD)"] == 0]
no_spend

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
5320,Dr.,Bruce,Bryan,ru@pubuspuh.cl,Male,59,Wal-Mart Stores Inc,Engineer Technician,(709) 446-8317,H6H 3Y0,NU,201000000000000,04/2024,Bankcard,0.0,White,82.70.62.64,Wednesday,am,12/11/1900
10597,Mrs.,Flora,Clark,wad@me.com,Female,27,MetLife Inc.,Cruise Director,(775) 373-6590,B2U 8K6,NB,30100000000000,05/2020,Diners Club Carte Blanche,0.0,Red,231.156.15.63,Thursday,pm,08/22/1904

**12. As a loyalty reward, company wants to send thanks coupon to those who spent 100CAD or more, please find out the customers?**

In [19]:
# Code here please

In [13]:
spent_100_plus = cust[cust["price(CAD)"] >= 100]
spent_100_plus

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
76,Mrs.,Gregory,Brown,hav@jek.gs,Female,31,"E*Trade Group, Inc.",Novelist,(625) 537-8923,X3S 4Q2,PE,6010000000000000,04/2018,Visa,100.0,Green,212.100.18.95,Monday,am,10/23/2063
21093,Mrs.,Cody,Christensen,get@jovu.ag,Male,28,National City Corp.,Hospital Administrator,(261) 737-3292,X0S 1O5,PE,201000000000000,03/2024,JCB,100.0,Green,168.48.19.165,Wednesday,pm,03/28/1955
24385,Miss,Lizzie,Dixon,goh@tuwjaz.gd,Female,38,FleetBoston Financial Co.,Compensation Analyst,(989) 239-1752,V8X 9V6,NB,6300000000000000,07/2019,Bankcard,100.0,Blue,140.87.99.78,Saturday,pm,03/03/1983

**13. How many emails are associated with this credit card number '5020000000000230'?**

In [20]:
# Code here please

In [14]:
cust[cust["cc_no"] == 5020000000000230]["email"].count()

np.int64(2)

**14. We need to send new cards to the customers well before the expire, how many cards are expiring in 2019?**<br>
*Use `sum()` and `count()` and see the difference in their use :)*

In [21]:
# Code here please

In [15]:
#cust[cust['cc_exp'].apply(lambda x: x[5:]) == '19'].count()
exp_2019 = cust[cust["cc_exp"].str[-4:] == "2019"].shape[0]
exp_2019

2684

**15. How many people use Visa as their Credit Card Provider?**

In [23]:
# Code here please

In [16]:
(cust["cc_type"] == "Visa").sum()

np.int64(1721)

**16. Can you find the customer who spent 100 CAD using Visa?**

In [24]:
# Code here please

In [17]:
visa_100 = cust[(cust["cc_type"] == "Visa") & (cust["price(CAD)"] >= 100)]
visa_100

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
76,Mrs.,Gregory,Brown,hav@jek.gs,Female,31,"E*Trade Group, Inc.",Novelist,(625) 537-8923,X3S 4Q2,PE,6010000000000000,04/2018,Visa,100.0,Green,212.100.18.95,Monday,am,10/23/2063

**17. What are two most common professions?**

In [25]:
# Code here please

In [18]:
cust["profession"].value_counts().head(2)

profession
Preschool Teacher       112
Distribution Manager    107
Name: count, dtype: int64

**18. Can you tell the top 5 most popular email providers? (e.g. gmail.com, yahoo.com, etc...)**

In [26]:
# Code here please

In [19]:
cust["email"].str.split("@").str[1].value_counts().head(5)

email
gmail.com      1687
me.com         1676
outlook.com    1664
live.com       1660
hotmail.com    1659
Name: count, dtype: int64

**19. Is there any customer who is using email with "am.edu"?**<br>
Hint: Use `lambda` expression in `apply()`. split the email address at `@`.

In [27]:
# Code here please

In [20]:
am_edu = cust[cust["email"].str.endswith("am.edu")]
am_edu

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
150,Miss,Loretta,Fletcher,barit@am.edu,Female,48,York International Corp,Rehabilitation Counselor,(323) 279-8038,E5X 8L0,QC,6330000000000000,05/2021,Diners Club United States & Canada,97.26,White,147.57.240.225,Monday,am,11/07/2066

**20. Which day of the week, the store gets more customers?**

In [28]:
# Code here please

In [21]:
cust["weekday"].value_counts().head(1)

weekday
Saturday    4376
Name: count, dtype: int64

# Excellent work!